:verbose: false
:concurrency: 25

:timeout: 8
:queues:
  - [default, 2]
  - mailers
  - scoring
:schedule:
  scoring_check:
    cron: '0 * * * * *'
    class: ScoringCheck
    queue: scoring
  guest_clear:
    cron: '20 17 1 * *'
    class: GuestClear
  set_matchday:
    cron: '10 0 * * *'
    class: SetMatchday
  matchday_times:
    cron: '15 1 * * *'
    class: MatchdayTimes
  lock_queuer:
    cron: '0 0 */12 * * *'
    class: LockQueuer
  reminder_queuer:
    cron: '5 0 * * *'
    class: ReminderQueuer