:verbose: false
:concurrency: 2

:timeout: 8
:queues:
  - default
  - mailers
:schedule:
  scoring_check:
    cron: '0 * * * * *'
    class: ScoringCheck
  guest_clear:
    cron: '0 20 17 1 * *'
    class: GuestClear
  set_matchday:
    cron: '0 10 0 * * *'
    class: SetMatchday
  matchday_times:
    cron: '0 15 0 */3 * *'
    class: MatchdayTimes
  lock_queuer:
    cron: '0 0 */12 * * *'
    class: LockQueuer
  reminder_queuer:
    cron: '0 5 0 * * *'
    class: ReminderQueuer