:verbose: false
:concurrency: 2

:timeout: 8
:queues:
  - default
  - mailers
:schedule:
  scoring_check:
    cron: '0 * * * * *'
    class: ScoringCheck
  guest_clear:
    every: '14d'
    class: GuestClear
  set_matchday:
    every: '24h'
    class: SetMatchday