:verbose: false
:concurrency: 2

:timeout: 8
:queues:
  - default
:schedule:
  scoring_check:
    cron: '0 * * * * *'
    class: ScoringCheck
  guest_clear:
    cron: '0 0 1 * * *'
    class: GuestClear
  set_matchday:
    cron: '0 0 * * * *'
    class: SetMatchday